### ISSUE TITLE
[Feature request] Mode to stop processing when moving to the next term

### ISSUE THREAD

**Issue by Slotos** [gelguy/wilder.nvim#110]
There are certain commands that are inherently slow to complete and unnecessary to do so once you get to a certain term.
A good example is Fugitive's `:Git fetch origin branch`. The last term is usually known before hand and it's likely the remote name that needs completion. Yet the moment completion is triggered on remote name, moving to branch name slows down to a crawl due to the need to fetch branch names.

Would it be possible to implement a mode of operations where wilder fully stops processing when it moves to the next term until completion is requested?

This is similar to #86 and #97, but features extra hoops.

**Comment by gelguy** [comment]
This is similar to #107 - what is happening is that the completion function for `Git fetch origin` takes a long time to complete and since we trigger the function each time the cmdline changes, it leads to a noticeable slowdown.

This can be worked around by stopping `wilder` when the cmdline matches `Git fetch origin`:
```
" Has to be added as the first branch.
call wilder#set_option('pipeline', [
      \ wilder#branch(
      \   [
      \     wilder#check({-> getcmdtype() ==# ':'}),
      \     {ctx, x -> x ~= 'Git fetch origin ' ? v:true : v:false},
      \   ],
      \  ... rest of the pipelines ...
      \ )])
```
What this config sets is when the cmdline starts with `Git fetch origin `, `wilder` will be hidden and the Neovim's inbuilt `wildmenu` will be used as the fallback (i.e. you can press `wildchar` to trigger the default `wildmenu`).
