### ISSUE TITLE
Wilder menu displays possible values, but going over them is done in separate window

### ISSUE THREAD

**Issue by ziombo** [gelguy/wilder.nvim#128]
Wilder memu shows up properly, but when I iterate over possible options a second windows pops up. I'm using Nvim v0.7.
![image](https://user-images.githubusercontent.com/15613606/162473418-660eaec0-9b74-46de-9a8c-f9a6f70637bb.png)
Wilder menu shows up properly

![image](https://user-images.githubusercontent.com/15613606/162473466-07ebbf90-23ab-4750-8697-544ca4ed2351.png)
When trying to go over the options a second window is put over wildermenu.

Using minimal config also makes the new window show up.
`call wilder#setup({'modes': [':', '/', '?']})`

![image](https://user-images.githubusercontent.com/15613606/162473856-2f1146b6-52fe-4028-b3a5-a05f5f66b3df.png)
![image](https://user-images.githubusercontent.com/15613606/162473872-424c58c3-9a92-4052-99aa-4e880dae7d12.png)

**Comment by gelguy** [comment]
Do you happen to have `nvim-cmp` and `cmp-cmdline` in your config? This will interfere with the bindings set by `wilder`.

Otherwise, could you provide a minimal `init.vim`?

**Comment by jdhao** [comment]
I have meet the same issue. I think it is because nvim-cmp is fucking up with cmdline mode because I see the `Tab` is hijacked by nvim-cmp (`:cmap <tab>`):

<img width="465" alt="image" src="https://user-images.githubusercontent.com/16662357/162582709-bc7bef08-5294-4b00-b505-7dde64f12919.png">

**Comment by jdhao** [comment]
I am not sure how to solve this issue. Nvim-cmp seems to hijack tab even if I instruct it to map Tab only in insert mode, related: https://github.com/hrsh7th/nvim-cmp/issues/880

**Comment by gelguy** [comment]
Thanks for the link to the `nvim-cmp` issue!

For @ziombo, note that you can also remove the `cmdline` setup for `nvim-cmp`. See https://github.com/gelguy/wilder.nvim/issues/120#issuecomment-1028187235.

**Comment by Gelio** [comment]
It looks like [this commit](https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558#diff-df823ce65cc2c7da6baceae5eeff942546e46b84c95571d897f0ba2f9f0385ddL40-L75) removes the default mapping for `<Tab>` and `<S-Tab>` from `nvim-cmp`. This means this issue should be solved, since `nvm-cmp` will no longer hijack those keys :tada: 

I updated to the latest version of `nvim-cmp` at the time of writing this comment, but unfortunately, it's broken (https://github.com/hrsh7th/nvim-cmp/issues/899), so we'll have to wait a bit before confirming that this is no longer a problem and we can use Tab with wilder.nvim without any problems

**Comment by wookayin** [comment]
> It looks like [this commit](https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558#diff-df823ce65cc2c7da6baceae5eeff942546e46b84c95571d897f0ba2f9f0385ddL40-L75) removes the default mapping for `<Tab>` and `<S-Tab>` from `nvim-cmp`. This means this issue should be solved, since `nvm-cmp` will no longer hijack those keys 🎉

Yes this is from today (April 13, 2022). Prior to that, one needed to explicitly configure cmdline mapping (see hrsh7th/nvim-cmp#880). These two configs are, unfortunately, not compatible with each other and mutually exclusive. See hrsh7th/nvim-cmp#897 for additional details.
