### ISSUE TITLE
popup menu rendered not working

### ISSUE THREAD

**Issue by gennaro-tedesco** [gelguy/wilder.nvim#38]
As described [here in the docs](https://github.com/gelguy/wilder.nvim#popupmenu-renderer-experimental-neovim-only) I am trying to default the rendered to popup menu: my configuration is the following
```
call wilder#set_option('renderer', wilder#popupmenu_renderer({
			\ 'highlights': wilder#basic_highlighter(),
			\ 'apply_highlights': wilder#query_common_subsequence_spans(),
			\ 'separator': ' · ',
			\ 'ellipsis': '...',
			\ 'left': [{'value': [
			\    wilder#condition(
			\      {-> getcmdtype() ==# ':'},
			\      ' COMMAND ',
			\      ' SEARCH ',
			\    ),
			\ ], 'hl': s:mode_hl,},
			\ wilder#separator('', s:mode_hl, s:hl, 'left'), ' ',
			\ ],
			\ 'right': [
			\    ' ', wilder#separator('', s:index_hl, s:hl, 'right'),
			\    wilder#index({'hl': s:index_hl}),
			\ ],
			\ }))
```
however, the popup is not showing up and neither are the suggestions on the statusline: is there any other option I have to set to have it working?

**Comment by gelguy** [comment]
There's a few problems wrong with the config, mostly caused by using `wilder#wildmenu_renderer()` options in `wilder#popupmenu_renderer()`:

1. `wilder#basic_highlighter()` should be under the `highlighter` option, not `highlights`. The `apply_highlights` option is deprecated in favour of `highlighter`, so you can remove that option. `wilder#query_common_subsequence_spans()` is also the old name of `wilder#basic_highlighter()`.
2. `separator` is not used in the popupmenu and should be removed
3. `left` and `right` take different kinds of arguments so the wildmenu items cannot be reused here.

This minimal config should work for you:
```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
			\ 'highlighter': wilder#basic_highlighter(),
			\ }))
```

To decorate the  popupmenu a bit more:
```vim
" wilder#popupmenu_devicons() needs 'ryanoasis/vim-devicons' to be installed
call wilder#set_option('renderer', wilder#popupmenu_renderer({
			\ 'highlighter': wilder#basic_highlighter(),
                        \ 'left': [
                        \   wilder#popupmenu_devicons(),
                        \   wilder#popupmenu_buffer_flags(),
                        \ ],
                        \ 'right': [
                        \   ' ',
                        \   wilder#popupmenu_spinner(),
                        \  wilder#popupmenu_scrollbar(),
                        \ ],
			\ }))
```

I did a big renaming of the API in #29 so for wildmenu the `left` or `right` items are prefixed with `wilder#wildmenu_...` and for popupmenu they are prefixed with `wilder#popupmenu...`. The old names can still be used for backwards compatability and I apologise if this created more confusion, but moving forward the new names should give a better indication of where they can be used.

**Comment by gennaro-tedesco** [comment]
Thank you, it works like a charm and looks great: I will be having a look at the changelog of #29 to be better informed. For reference (if someone else comes across this issue) I am using:
```
call wilder#set_option('renderer', wilder#renderer_mux({
      \ ':': wilder#popupmenu_renderer({
		\ 'highlighter': wilder#basic_highlighter(),
      \ }),
      \ '/': wilder#wildmenu_renderer(
      \ wilder#lightline_theme({
      \   'highlights': {},
      \   'highlighter': wilder#basic_highlighter(),
      \   'separator': ' · ',
      \ })
      \ ),
      \ }))
```
One last question: is it possible to determine the height of the popup menu when it opens, namely to customise how many items are being shown at a first glance?

**Comment by gelguy** [comment]
Yes, the `max_height` option does this.

You can set it to a string e.g. `'50%'` so it takes up to 50% of Neovim's height or to a number `20` (note: no quotes) so it takes up to 20 lines in height.

`:h wilder#popupmenu_renderer()` will describe more of the other options (e.g. `max_width`).

**Comment by gennaro-tedesco** [comment]
Awesome, this will do. Feel free to close this issue! :)
