### ISSUE TITLE
Fuzzy finder only matches from the first letter onward.

### ISSUE THREAD

**Issue by luiz00martins** [gelguy/wilder.nvim#66]
When typing a pattern, the fuzzy finder only matches words that begin with the first letter of the pattern.

In this example, the pattern "`term`" matches with the word `ctermfg`, but the fuzzy finder will not show it, since it will only show matches that begin with the letter "`t`":
![Screenshot from 2021-08-12 14-12-16](https://user-images.githubusercontent.com/43142209/129239640-c9de6485-559e-4729-898b-362857e1c37d.png)

 I can also confirm that `ctermfg` is indexed by wilder, since typing "`cter`" shows it:
![Screenshot from 2021-08-12 14-19-28](https://user-images.githubusercontent.com/43142209/129240489-0838933f-acdb-442e-81f2-0d27ac556e7b.png)

It'd be nice if we had the option to enable a broader matching style for the fuzzy finder, which included words that do not begin with first letter of the pattern.

**Comment by gelguy** [comment]
If you're using the `python_search_pipeline`, there's already an option for that:
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline(),
      \     wilder#python_search_pipeline({
      \       'pattern': wilder#python_fuzzy_pattern({
      \         'start_at_boundary': 0,
      \       }),
      \       'engine': 're',
      \     }),
      \   ),
      \ ])
```
The `pattern` option can also take a function if you need to customise it further. See `:h wilder#python_search_pipeline()`.

Note 1: `start_at_boundary: 0` slows down the regex matching by a lot since it introduces a lot of backtracking.

Note 2: I highly recommend using `re2` as the engine for performance reasons. It can be installed with `pip install pyre2`.

For `vim_search_pipeline`, I don't intend to add fuzzy matching as the searching is synchronous and Vim's regex engine is not as fast.

**Comment by gelguy** [comment]
`start_at_boundary` only applies to the pattern in `wilder#python_search_pipeline()`.

To get the same effect for `wilder#cmdline_pipeline()`, set `'fuzzy': 2`:
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline({'fuzzy': 2}),
      \     wilder#python_search_pipeline({
      \       'pattern': wilder#python_fuzzy_pattern({
      \         'start_at_boundary': 0,
      \       }),
      \       'engine': 're',
      \     }),
      \   ),
      \ ])
```

**Comment by goduck777** [comment]
Thank you! works as expected.
